version: '3.6'
services:

    mariadb1:
        image: mariadb
        container_name: mariadb-01
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=supersecret
            - MYSQL_DATABASE=db1
            - MYSQL_USER=db1user
            - MYSQL_PASSWORD=secret

    wordpress1:
        image: wordpress
        container_name: wordpress-01
        volumes:
            - ./wp_data:/var/www/html
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        depends_on:
            - mariadb1
        restart: always
        environment:
            - WORDPRESS_DB_HOST=mariadb1:3306
            - WORDPRESS_DB_NAME=db1
            - WORDPRESS_DB_USER=db1user
            - WORDPRESS_DB_PASSWORD=secret
            - WORDPRESS_TABLE_PREFIX=wp_
            - VIRTUAL_HOST=site1.com
            - LETSENCRYPT_HOST=site1.com
            - LETSENCRYPT_EMAIL=admin1@email.com

networks:
  default:
    external:
      name: dockernet